Решение 2.1
DenisMacflurry/TKI-142 pull request #9
Opened 2024-10-28 10:55 UTC by DenisMacflurry

Решение 2.1 #8

2024-10-28 11:48 UTC, MarinaPaley requested changes

2024-10-28 11:48 UTC, MarinaPaley commented on task2.1.c
> +        }
default

2024-11-25 10:53 UTC, DenisMacflurry commented on task2.1.c
> +        }
добавил

2024-11-27 14:36 UTC, MarinaPaley requested changes

2024-11-27 14:36 UTC, MarinaPaley commented on task2.1.c
> +    printf("Что вы хотите узнать?\n Площадь грани куба - 1 \n Площадь полной поверхности - 2\n Объем куба - 3 \n");
Не надо использовать _&laquo;магические константы&raquo;_ в коде. Это не только признак дурновкусия, но и источник большого числа потенциальных ошибок. Привожу некоторые источники, потребные для Вашего самообразования:
- [ru.wikipedia.org](https://ru.wikipedia.org/wiki/Магическое_число_(программирование))
- [refactoring.guru](https://refactoring.guru/ru/replace-magic-number-with-symbolic-constant)
- [pvs-studio.com](https://pvs-studio.com/ru/blog/posts/cpp/0023/)
- [habr.com](https://habr.com/ru/post/328244/)

2024-11-27 14:36 UTC, MarinaPaley commented on task2.1.c
> +            break;
Разница между break, return  и exit (abort)!

2024-12-18 17:18 UTC, closed without merging